Tests for CompaniesSlicDAO and GroupsDAO
dataengi/crm-seed pull request #17
Opened 2017-12-15 13:34 UTC by Liudmila19

## Purpose
Writing tests for DAO

## Approach
Increases the percentage coverage of the code by tests

## Short description 
Writing tests for covering  the code

2017-12-15 13:55 UTC, slmzig commented on docker-compose-dev.yml
> -      SERVER_ADDRESS: "http://10.20.10.104:9000"
Why did you change this?

2017-12-15 13:55 UTC, slmzig commented on test/com/dataengi/crm/contacts/daos/contacts/ContactsDAOSpec.scala
> +
Did you use code formatting?

2017-12-15 15:16 UTC, AndriiStefaniv requested changes

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/contacts/daos/GroupsDAOSpec.scala
> +      getGroupByIdResult.isRight === true
maybe test steps must be
- insert few group into empty storage
- call `all`
- check elements of list

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/contacts/daos/GroupsDAOSpec.scala
> +      val groups                   = Gen.listOfN(10, groupArbitrary.arbitrary).sample.get.map(_.copy(contactsBookId = testContactsBookId))
Extract `Gen.listOfN(10, groupArbitrary.arbitrary)` to function

Somethink like
```scala
def groupsGen(n: Int) = Gen.listOfN(n, groupArbitrary.arbitrary)
def generateGroups(n: Int) = groupsGen(n).sample.get
```

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val getByIdCompany = companiesDAO.get(466).await()
What's magic number `466`?

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val getByIdCompany = companiesDAO.get(466).await()
Random integer?

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      getByIdCompany must beLeft(CompaniesDAOError("Company not found in companies table"))
Prefer
```scala
import com.dataengi.crm.identities.daos.errors.CompaniesDAOErrors

...

getByIdCompany must beLeft(CompaniesDAOErrors.CompanyNotFound)
```

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      result must beLeft(CompaniesDAOError("Can not do action because company doesn't exist"))
Prefer
```scala
import com.dataengi.crm.identities.daos.errors.CompaniesDAOErrors

...

getByIdCompany must beLeft(CompaniesDAOErrors.CompanyIdIsEmpty)
```

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val CompanyList      = List(company1, company2)
Prefer name `companies`

https://github.com/awesome-it-ternopil/best-practices/wiki/Scala-best-practice#variable-naming-convention

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val id1            = addCompanyResult.right.get.head
If `addCompanyResult.value` be empty then we will get error.

Would be better add check begore
```scala
      val companiesDB = addCompanyResult.value

      companiesDB must have size 2

      val id1            = companiesDB.head
      val id2            = companiesDB.last
```

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      getByIdCompany.isRight === true
maybe test steps must be
- insert few companies into empty storage
- call all
- check elements of list

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val updateForCompany    = Company("updatedcompany").copy(id = Some(companyId))
Prefer
```scala
Company("updatedcompany", id = Some(companyId))
```

2017-12-15 15:16 UTC, AndriiStefaniv commented on test/com/dataengi/crm/profiles/daos/ProfilesDAOSpec.scala
> +      getProfileResult.isRight === true
Prefer
```scala
      val getProfileResult = profilesDAO.get(addResult.value).await()
      getProfileResult must beRight(...)
```

2017-12-28 13:14 UTC, Liudmila19 commented on test/com/dataengi/crm/contacts/daos/GroupsDAOSpec.scala
> +      getGroupByIdResult.isRight === true
changed

2017-12-28 13:23 UTC, Liudmila19 commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val CompanyList      = List(company1, company2)
done

2017-12-28 13:35 UTC, NK91 commented on test/com/dataengi/crm/contacts/daos/GroupsDAOSpec.scala
> +      val groups                   = Gen.listOfN(10, groupArbitrary.arbitrary).sample.get.map(_.copy(contactsBookId = testContactsBookId))
in `com.dataengi.crm.common.extensions` we have
```scala
class ArbitraryValueExtensions[T](val arbitrary: Arbitrary[T]) extends AnyVal {

  def value: T = arbitrary.arbitrary.sample.get

  def list(size: Int): List[T] = Gen.listOfN(size, arbitrary.arbitrary).sample.get

}
```

2017-12-28 13:37 UTC, NK91 commented on test/com/dataengi/crm/contacts/daos/GroupsDAOSpec.scala
> +      val groups                   = Gen.listOfN(10, groupArbitrary.arbitrary).sample.get.map(_.copy(contactsBookId = testContactsBookId))
so we can do the next:
```scala
import com.dataengi.crm.common.extensions.arbitrary._
val groups = groupArbitrary.list(10)
```

2017-12-28 14:37 UTC, NK91 commented on app/com/dataengi/crm/identities/daos/CompaniesSlickDAO.scala
> +  def clear: EmptyOr
Why do you need clear here?

2018-01-05 13:46 UTC, Liudmila19 commented on test/com/dataengi/crm/contacts/daos/contacts/ContactsDAOSpec.scala
> +
done

2018-01-05 14:16 UTC, AndriiStefaniv submitted a review, later dismissed

2018-01-05 14:35 UTC, Liudmila19 commented on app/com/dataengi/crm/identities/daos/CompaniesSlickDAO.scala
> +  def clear: EmptyOr
I need this for tests

2018-01-05 15:32 UTC, NK91 commented on test/com/dataengi/crm/profiles/daos/ProfilesDAOSpec.scala
> +      val getProfileResult = profilesDAO.getOption(24254625625L).await()
try to avoid the magic number
extract it to value `NonExistId` or take max Int value

2018-01-05 15:32 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      println(s"[companies-dao][add] $addCompanyResult}")
remove `println` it's only for debug propose

2018-01-05 15:32 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/CompaniesDAOSpec.scala
> +      val result = companiesDAO.update(Company("test")).await()
try to extract String to some value

2018-01-10 08:14 UTC, NK91 submitted a review, later dismissed

2018-01-10 08:31 UTC, NK91 approved these changes

2018-01-10 08:38 UTC, merged