Tests for InMemoryPasswordInfoDAO
dataengi/crm-seed pull request #18
Opened 2017-12-15 13:50 UTC by m-tetiana

## Purpose
Writing tests for password info DAO in memory

## Approach
Increases the percentage coverage of the code by tests

## Short description 
Writing tests for covering the code

2017-12-15 14:39 UTC, AndriiStefaniv requested changes

2017-12-15 14:39 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOTest.scala
> +  lazy val passwordInfo = PasswordInfo("testHasher", "password", Some("testSalt"))
It would be better to generate `LoginInfo` and `PasswordInfo` in each case

2017-12-15 14:39 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOTest.scala
> +      val addUserInfo: PasswordInfo               = Await.result(addUserInfoFuture, 10 seconds)
Logic duplicated in many test cases
```scala
val addUserInfoFuture: Future[PasswordInfo] = passwordInfoDAO.add(loginInfo, passwordInfo)
val addUserInfo: PasswordInfo               = Await.result(addUserInfoFuture, 10 seconds)
```
Can be extracted to function or scope

2017-12-18 09:26 UTC, AndriiStefaniv submitted a review, later dismissed

2017-12-18 10:06 UTC, molitskyi commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +    println(passwordInfo)
Remove `println(...)`

2017-12-18 11:00 UTC, molitskyi submitted a review, later dismissed

2017-12-18 11:36 UTC, AndriiStefaniv submitted a review, later dismissed

2017-12-22 12:52 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +  override lazy val fakeModule = new FakeModule {
I think we don't need to override fake module here

2017-12-22 12:52 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +  override lazy val fakeModule = new FakeModule {
It can be removed

2017-12-22 12:52 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +      val resultPasswordInfo       = Await.result(resultPasswordInfoFuture, 10 seconds)
Await.result we have extension for `Or` type
for future spec2 have some `matchers`

2017-12-22 12:52 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +      addUserInfo(loginInfo)
what do we check here?

2017-12-22 12:52 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/InMemoryPasswordInfoDAOSpec.scala
> +    Await.result(addUserInfo, 10 seconds) === passwordInfo
better to use `addUserInfo.await()` look at spec2 matchers

2017-12-28 14:34 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val loginInfo          = loginInfoArbitrary.arbitrary.sample.get
we have an extension for it 
```scala
import import com.dataengi.crm.common.extensions.arbitrary._
...
val loginInfo = loginInfoArbitrary.value
```

2017-12-28 14:34 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val loginInfo          = loginInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val loginInfo = loginInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val loginInfo = loginInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val passwordInfoForUpdate = passwordInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +      val loginInfo = loginInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +    val passwordInfo = passwordInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +    val user = User(loginInfo, companyArbitrary.arbitrary.sample.get, roleArbitrary.arbitrary.sample.get)
here the same

2017-12-28 14:35 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +    val passwordInfo = passwordInfoArbitrary.arbitrary.sample.get
here the same

2017-12-28 15:40 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/PasswordInfoDAOSpec.scala
> +    val user = User(loginInfo, companyArbitrary.arbitrary.sample.get, roleArbitrary.arbitrary.sample.get)
`companyArbitrary.arbitrary.sample.get` -> `companyArbitrary.arbitrary.value` and 
`roleArbitrary.arbitrary.sample.get` -> `roleArbitrary.arbitrary.value`

2017-12-28 15:49 UTC, NK91 approved these changes

2017-12-28 15:55 UTC, AndriiStefaniv approved these changes

2017-12-28 15:57 UTC, merged