Create tests to UsersDao
dataengi/crm-seed pull request #19
Opened 2017-12-15 14:02 UTC by Akanteruk

## Short description 
Creation tests for an increasing coverage of code

2017-12-15 14:30 UTC, AndriiStefaniv requested changes

2017-12-15 14:30 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val newCompany                      = companiesService.get(newCompanyResult.value).await().value
Logic of creating company is duplicated in each test case.

Code:
```scala
val NewCompanyName: String          = "NEW_COMPANY" + Gen.alphaStr.sample.get
val newCompanyResult: XorType[Long] = companiesService.create(NewCompanyName).await()
val newCompany                      = companiesService.get(newCompanyResult.value).await().value
```
can be extracted to function
```scala
def createCompany(): Company = {
   val NewCompanyName: String          = "NEW_COMPANY" + Gen.alphaStr.sample.get
   val newCompanyResult: XorType[Long] = companiesService.create(NewCompanyName).await()
   val getCompanyResult                = companiesService.get(newCompanyResult.value).await().value

   getCompanyResult.isRight === true
 
   val company = getCompanyResult.value

   company.id must not be None
   company
}
```
Then in each case

```scala
"find user by companyId negative" in {
  val company   = createCompany()
  val companyId = newCompany.id.get
...
}
```

2017-12-15 14:30 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val updateUser       = User(loginInfo = TestLoginInfo5, company = newCompany, role = role).copy(id = Some(56667))
Can be
```scala
User(loginInfo = TestLoginInfo5, company = newCompany, role = role, id = Some(56667)
```

2017-12-15 14:30 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +  val TestLoginInfo2: LoginInfo = LoginInfo("provider2", "dasd2@asd.com")
Maybe it will be better generating `TestLoginInfo*` in each test case. Not same for all cases

2017-12-15 14:30 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val NewCompanyName: String          = "NEW_COMPANY" + Gen.alphaStr.sample.get
Prefer name `newCompanyName`

https://github.com/awesome-it-ternopil/best-practices/wiki/Scala-best-practice#naming-convention

2017-12-19 08:48 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +//      val user: User = createUserWithRole("user1","user1@test.com").await().right.get
Don't leave commented code

2017-12-19 08:48 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val TestLoginInfo2: LoginInfo = LoginInfo("provider2", "dasd2@asd.com")
If `TestLoginInfo2` is unused then delete it

2017-12-19 08:48 UTC, AndriiStefaniv commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val role                            = rolesService.find(RolesConfiguration.CompanyManager.name).await().value
please use autoformat

2017-12-19 08:58 UTC, molitskyi commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val key = getUserResult.right.get
Use `getUserResult.value` instead `getUserResult.right.get`

2017-12-19 09:03 UTC, molitskyi commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val key = getUserResult.right.get
`getUserResult.value`

2017-12-19 09:04 UTC, molitskyi commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      getOptionUserResult.right.get.get.loginInfo === user.loginInfo
`getOptionUserResult.value` instead `getOptionUserResult.right.get`

2017-12-19 10:00 UTC, AndriiStefaniv approved these changes

2017-12-19 10:13 UTC, molitskyi commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      val users = usersDAO.findByCompany(companyId).await().right.get
`.value` instead `.right.get`

2017-12-22 09:43 UTC, molitskyi approved these changes

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +  lazy val usersDAO = application.injector.instanceOf[UsersDAO]
I think it's better to refactor into scope or test fixture

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      company.id must not be None
company.id.nonEmpty ?

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      println(s"[user-dao][find] ${findUserResult.logResult}")
remove `println`
it's only for debug propose

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      findUserResult.isRight === true
if you have to check of some result value, you don't need always check is it `right`

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      println(s"[user-dao][get] ${getUserResult.logResult}")
remove

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      getOptionUserResult.isRight === true
don't need check here

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      getUser.isRight === true
don't need check here

2017-12-22 12:47 UTC, NK91 commented on test/com/dataengi/crm/identities/daos/UsersDAOSpec.scala
> +      getUser.isRight === true
don't need check here

2018-01-05 13:44 UTC, NK91 approved these changes

2018-01-05 13:45 UTC, merged